name: Release

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x

    - name: Build
      run: |
        npm install
        webpack --mode production
    - name: Upload artifact
      uses: actions/upload-artifact@v4.4.3
      with:
          name: bundle.js
          path: dist/
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Download artifact
      uses: actions/download-artifact@v4.1.8
      with:
        name: bundle.js

    - name: Test
      run: |
        ls
